In [2]:
import os
import torch
os.environ['TORCH'] = torch.__version__
print(torch.__version__)

!pip install -q torch-scatter -f https://data.pyg.org/whl/torch-${TORCH}.html
!pip install -q torch-sparse -f https://data.pyg.org/whl/torch-${TORCH}.html
!pip install -q git+https://github.com/pyg-team/pytorch_geometric.git

1.11.0+cu113
     |████████████████████████████████| 7.9 MB 26.1 MB/s 
     |████████████████████████████████| 3.5 MB 52.1 MB/s 


In [3]:
from torch_geometric.datasets import Planetoid

dataset = Planetoid(root='tmp', name='Cora')

Processing...
Done!


In [4]:

import torch.nn.functional as F
from torch.nn import Sequential, Linear, ReLU
import torch_geometric
from torch_geometric.nn import GCNConv

In [5]:
class GCNNet(torch.nn.Module):
    def __init__(self, dataset):
        super(GCNNet, self).__init__()
        self.conv1 = GCNConv(dataset.num_node_features, 16)
        self.conv2 = GCNConv(16, dataset.num_classes)

    def forward(self, x, edge_index):
        x = self.conv1(x, edge_index)
        x = F.relu(x)
        x = F.dropout(x, training=self.training)
        x = self.conv2(x, edge_index)

        return F.log_softmax(x, dim=1)



In [8]:

def retrieve_accuracy(model, data, test_mask=None, value=False):
    _, pred = model(data.x, data.edge_index).max(dim=1)
    if test_mask is None:
        test_mask = data.test_mask
    correct = float(pred[test_mask].eq(data.y[test_mask]).sum().item())
    acc = correct / test_mask.sum().item()
    if value:
        return acc
    else:
        return 'Accuracy: {:.4f}'.format(acc)

In [9]:
def save_model(model, path):
    torch.save(model.state_dict(), path)

In [10]:
def train_model(model, data, epochs=200, lr=0.01, weight_decay=5e-4, clip=None, loss_function="nll_loss",
                epoch_save_path=None, no_output=False):
    optimizer = torch.optim.Adam(model.parameters(), lr=lr, weight_decay=weight_decay)

    accuracies = []

    model.train()
    for epoch in range(epochs):
        optimizer.zero_grad()
        out = model(data.x, data.edge_index)
        if loss_function == "nll_loss":
            loss = F.nll_loss(out[data.train_mask], data.y[data.train_mask])
        elif loss_function == "cross_entropy":
            loss = F.cross_entropy(out[data.train_mask], data.y[data.train_mask], size_average=True)
        else:
            raise Exception()
        if clip is not None:
            torch.nn.utils.clip_grad_norm(model.parameters(), clip)
        loss.backward()
        optimizer.step()

        if epoch_save_path is not None:
            # circumvent .pt ending
            save_model(model, epoch_save_path[:-3] + "_epoch_" + str(epoch) + epoch_save_path[-3:])
            accuracies.append(retrieve_accuracy(model, data, value=True))
            print('Accuracy: {:.4f}'.format(accuracies[-1]), "Epoch", epoch)
        else:
            if epoch % 25 == 0 and not no_output:
                print(retrieve_accuracy(model, data))

    model.eval()

    return accuracies

In [14]:
model = GCNNet(dataset)
data = dataset[0]
acc = train_model(model, data, epochs=200, lr=0.01, weight_decay=5e-4, clip=None, loss_function="nll_loss",
                epoch_save_path=None, no_output=False)
test_acc =  retrieve_accuracy(model, data, test_mask=None, value=True)
print("Test Accuracy:",test_acc)

Accuracy: 0.3480
Accuracy: 0.7170
Accuracy: 0.7210
Accuracy: 0.7380
Accuracy: 0.7630
Accuracy: 0.7700
Accuracy: 0.7580
Accuracy: 0.7590
Test Accuracy: 0.811


In [22]:
def execute_model_with_gradient(model, node, x, edge_index):
    ypred = model(x, edge_index)

    predicted_labels = ypred.argmax(dim=-1)
    predicted_label = predicted_labels[node]
    logit = torch.nn.functional.softmax((ypred[node, :]).squeeze(), dim=0)

    logit = logit[predicted_label]
    loss = -torch.log(logit)
    loss.backward()

In [23]:
def grad_node_explanation(model, node, x, edge_index):
    model.zero_grad()

    num_nodes, num_features = x.size()

    node_grad = torch.nn.Parameter(torch.ones(num_nodes))
    feature_grad = torch.nn.Parameter(torch.ones(num_features))

    node_grad.requires_grad = True
    feature_grad.requires_grad = True

    mask = node_grad.unsqueeze(0).T.matmul(feature_grad.unsqueeze(0)).to(device)

    execute_model_with_gradient(model, node, mask*x, edge_index)

    node_mask = torch.abs(node_grad.grad).cpu().detach().numpy()
    feature_mask = torch.abs(feature_grad.grad).cpu().detach().numpy()

    return feature_mask, node_mask


In [28]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

feature_mask, node_mask = grad_node_explanation(model,1,data.x, data.edge_index)
print("feature masks:",feature_mask)
print("node masks:",node_mask)

feature masks: [0. 0. 0. ... 0. 0. 0.]
node masks: [0.0000000e+00 1.6197766e-04 3.0046589e-05 ... 0.0000000e+00 0.0000000e+00
 0.0000000e+00]


In [ ]:
import torch
random_seed=1234
num_nodes=10
samples=5
num_nodes_computation_graph = 5
num_features=10
device ='cpu'
rng = torch.Generator(device=device)
rng.manual_seed(random_seed)
random_indices = torch.randint(num_nodes, (samples, num_nodes_computation_graph, num_features),
                                generator=rng,
                                device=device,
                                )
random_indices = random_indices.type(torch.int64)

print(random_indices[0])

full_feature_matrix = torch.rand(10,10)

print(full_feature_matrix)
random_features = torch.gather(full_feature_matrix,
                                dim=0,
                                index=random_indices[0, :, :])



print(random_features)

In [2]:
import torch
random_seed=1234
num_edges=20
samples=5
num_edges_computation_graph = 5
device ='cpu'
rng = torch.Generator(device=device)

rng.manual_seed(random_seed)

random_indices = torch.randint(num_edges, (samples, num_edges_computation_graph),
                                generator=rng,
                                device=device,
                                )
random_indices = random_indices.type(torch.int64)

print(random_indices[0])

full_edge_mask= torch.rand(20)

print(full_edge_mask)
random_edge_mask = torch.gather(full_edge_mask,
                                dim=0,
                                index=random_indices[0, :])



print(random_edge_mask)

tensor([15, 11,  6,  5, 16])
tensor([0.4687, 0.4148, 0.7307, 0.0941, 0.6140, 0.8260, 0.9967, 0.5046, 0.5464,
        0.8469, 0.9034, 0.0642, 0.8949, 0.3981, 0.0316, 0.2613, 0.6488, 0.9549,
        0.0277, 0.0824])
tensor([0.2613, 0.0642, 0.9967, 0.8260, 0.6488])
